// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2eEjrWJtx2kgsr7aE3UYU5dAqEIhHsM0',
    appId: '1:268973299952:web:6235ddf4247dc2b1f8ca35',
    messagingSenderId: '268973299952',
    projectId: 'mesquita-40d71',
    authDomain: 'mesquita-40d71.firebaseapp.com',
    storageBucket: 'mesquita-40d71.firebasestorage.app',
    measurementId: 'G-241QDFV9VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWi6Q5iGtMqY7hNDHyF9SG3pkWJ7eAD8U',
    appId: '1:268973299952:android:7b6f87b347ec869cf8ca35',
    messagingSenderId: '268973299952',
    projectId: 'mesquita-40d71',
    storageBucket: 'mesquita-40d71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_ZEkqN37jzGpg8llNZgOcXqneQQNfzQ',
    appId: '1:268973299952:ios:7ad0b5e01355f2aef8ca35',
    messagingSenderId: '268973299952',
    projectId: 'mesquita-40d71',
    storageBucket: 'mesquita-40d71.firebasestorage.app',
    iosBundleId: 'com.example.mesquitaQuelimane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_ZEkqN37jzGpg8llNZgOcXqneQQNfzQ',
    appId: '1:268973299952:ios:7ad0b5e01355f2aef8ca35',
    messagingSenderId: '268973299952',
    projectId: 'mesquita-40d71',
    storageBucket: 'mesquita-40d71.firebasestorage.app',
    iosBundleId: 'com.example.mesquitaQuelimane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2eEjrWJtx2kgsr7aE3UYU5dAqEIhHsM0',
    appId: '1:268973299952:web:806a578dd836ef29f8ca35',
    messagingSenderId: '268973299952',
    projectId: 'mesquita-40d71',
    authDomain: 'mesquita-40d71.firebaseapp.com',
    storageBucket: 'mesquita-40d71.firebasestorage.app',
    measurementId: 'G-5YCCKZV6JP',
  );
}
